spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fai7h01/config-repo.git
          default-label: master
          username: fai7h01
          password: ${config-service-token}


server:
  port: 8888